### ISSUE TITLE
Can't insert charts from Array

### ISSUE THREAD

**Issue by BojackTSP** [cxn03651/write_xlsx#34]
I am trying to create multiple charts, and don't want to have to code them all by hand so I tried to create them all into an array, then loop through the array to insert them all.  I the charts being created properly, and I run through a .each_with_index loop on the array containing the charts. When the output file is saved, the following error/stack trace comes up

>! C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/utility.rb:36:in 'xl_cell_to_rowcol': undefined method 'split' for nil:NilClass (NoMethodError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/workbook.rb:1134:in 'get_chart_range'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/workbook.rb:1657:in 'block (2 levels) in add_chart_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/workbook.rb:1645:in 'each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/workbook.rb:1645:in 'block in add_chart_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/workbook.rb:1644:in 'each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/workbook.rb:1644:in 'add_chart_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/workbook.rb:1288:in 'store_workbook'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/write_xlsx-0.83.0/lib/write_xlsx/workbook.rb:159:in 'close'
        from D:/userpath/lib/adaa/xlsxbuilder.rb:571:in `exportFile'
        from exe/adaa:471:in `run'
        from exe/adaa:478:in `<main>

My exportFile method is just a call to close the workbook.  The "offending code" as I have been able to find is the following loop (added in the variables initializations though I skipped over the creation of the charts, as I have tested them individually and the issue does not lie there)

```charts = [ ]
locLegend = ["A1", "A16", "A31", "I1", "I16", "I31"]
...
charts.each_with_index do |chart, idx|
    @worksheet.insert_chart(locLegend[idx], chart)
end
```

**Comment by BojackTSP** [comment]
I have resolved the issue, it was a miss-located counter variable on my part, nothing on your end.  Closing issue
